fixtures:
  repositories:
  forge_modules:
    augeas: "camptocamp/augeas"
    stdlib: "puppetlabs/stdlib"
    inifile: "puppetlabs/inifile"
    augeasproviders_core: "herculesteam/augeasproviders_core"
    augeasproviders_postgresql: "herculesteam/augeasproviders_postgresql"
  symlinks:
    pgpool: "#{source_dir}"
